### ISSUE TITLE
Rename to decompyle 

### ISSUE THREAD

**Issue by Suya1671** [Numenorean/exe2py#2]
As soon as I saw this I though that would be a cool idea.

**Comment by xxxzsx** [comment]
https://github.com/xxxzsx/bin2py

**Comment by xxxzsx** [comment]
Done #3

**Comment by xxxzsx** [comment]
Resolved, close issue ⚡️

**Comment by ghost** [comment]
@Numenorean Resolved, close issue ⚡️
